### ISSUE TITLE
Data Extractor has stopped updating data

### ISSUE THREAD

**Issue by FBueckert** [Morta1/IdleonToolbox#110]
The data extractor still continues to function, but no longer updates data in the toolbox.

This happened a couple patches ago, so I'm assuming it has something to do with an updated format.  When I try to export from the extractor, it copies files to the target DB and generates JSON.  But it is also telling me the data is old, and the last update was 16/07/2022.

Looking around for cloud saves, it doesn't appear IdleOn uses Steam Cloud, so I'm at a loss for what might be the issue.

**Comment by Morta1** [comment]
This is what I'm getting, maybe try to re-download the extractor

![image](https://user-images.githubusercontent.com/18611518/180620596-6526fdcb-ac6c-420c-ac6b-ae06256bb314.png)
![image](https://user-images.githubusercontent.com/18611518/180620600-a9c427f2-8c0a-4b08-b94e-20e0da829dc8.png)

**Comment by Morta1** [comment]
That is really weird, it's the first time hearing about this kind of problem and it doesn't seem to replicate for other people.
The only thing I can think of is maybe try to run the program as an admin.

As an alternative you can try to use the email + password login (if you're not registered with gmail)
![image](https://user-images.githubusercontent.com/18611518/180929032-190acdc6-458c-4bbd-9f2d-96be8aa23356.png)

**Comment by Danthar** [comment]
Same issue here. Firefox: Getting this error in the JS console.
![afbeelding](https://user-images.githubusercontent.com/986519/182830777-1d6fe37c-9f7e-4ac5-99f9-5bae5c50a6d6.png)

**Comment by Danthar** [comment]
Clearing all site data fixed that issue. Now there are clipboard errors. I figured out its because i updated to a newer version of FireFox. The latest version does no longer allow clipboard access via javascript. Because its seen as a massive security risk. Its also part of a W3C spec, so i expect other browsers to follow with the same behavior soonish.
You might be better of providing an alternative. Like a seperate page that simply shows a large textbox in which a user can paste his state, and then clicks a button to import it. That way you can avoid directly accessing the clipboard.

**Comment by Morta1** [comment]
I've already added support for firefox.
After clicking on the paste json button you will see an option to paste your data into an input and upload it.
![image](https://user-images.githubusercontent.com/18611518/182846482-07e29f0c-9df5-427c-bbfb-1d73c22bf1ed.png)

**Comment by Danthar** [comment]
Oh lol.
Yeah that wasn't very clear to me :D. But yeah, that works.
